apiVersion: argoproj.io/v1alpha1
Kind: Application
metadata:
  name: myapp-argo-application
  namesapece: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/haythem05/frontend.git
    targetRevision: main
    path: Frontend
  destination:
    server: https://kubernetes.default.svc
    namesapece: myapp
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true